### PR TITLE
chore: update SDK to develop version

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
During testing, I found the following errors:
This error appeared constantly:
ok errr
ok error

No connection with sh UI. I clicked on create a new post in the sh feed and was redirected to the extension. When I tried to go back I got the following error:
errr in ff ext
t error
mainteinance error on th eui

All my .chain names have disappeared from the wallet. No names found:
no names found

No connection with Jelly Swap. There are no URLs in the permission settings for Jelly Swap, UI testing, etc.

Broken manifest for chrome extension, can't install it.

These errors also remain #1028 https://github.com/aeternity/superhero-wallet/issues/907#issuecomment-809553301

**Comment by Liubov-crypto** [comment]
Got this error after clicking on the Notifications bell icon and after sending ae from the main account to sub-account in the wallet (although the transaction was made):
sub acc wal
send ae from 1 acc to sub acc in the wallet
bell icon
bell


Tx history appears with delay in sub-accounts:

https://user-images.githubusercontent.com/69896204/116556845-96cf5480-a906-11eb-829e-88ae75da62c1.mov

After the registration, the name disappears, does not hang as a pending in the wallet (herosuperhero.chain):
th_2iDFdZ8zF5W7hPfvVQeuWz9Zzp1vgJ42bwVZd3FBjbw9JH7kHX

**Comment by davidyuk** [comment]
Should be fixed:
- OK exception
- ability to install into Chrome

**Comment by Liubov-crypto** [comment]
if I click on Receive in Balances, then there is no QR code:
receive error

when sending tokens, the wallet turns black, then everything works again:
https://user-images.githubusercontent.com/69896204/116678168-b3749680-a9b1-11eb-9bc4-d8fc08f5329b.mov

Design bug: 
design bug

Should be fixed:
* OK exception - fixed
* Ability to install into Chrome - fixed
* connection with Jelly Swap - fixed  May be fixed (can't reproduce):
* chain names have disappeared - fixed

**Review by etharner — APPROVED** [review]

**Pull request merged**
