### PR TITLE
Refactor popups

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Found these bugs while testing:
поп ап

error  when testing

Design related - white stripe in FF: 
white stripe in web wallet

**Comment by davidyuk** [comment]
> Design related - white stripe in FF

This one comes from the develop branch

**Comment by davidyuk** [comment]
I have fixed the first bug above by using a different modal as a base for the united one.

The second one was because of missed `amount` converted in SignDetailsList.

@Liubov-crypto please recheck it after tests are complete

**Comment by Liubov-crypto** [comment]
> I have fixed the first bug above by using a different modal as a base for the united one.
> 
> The second one was because of missed `amount` converted in SignDetailsList.
> 
> @Liubov-crypto please recheck it after tests are complete

Rechecked, in general LGTM.

In a web wallet, the pop-up should be on the whole page? is this correct?
full screen

**Review by CedrikNikita — APPROVED** [review]
Code changes look good

**Pull request merged**
