### PR TITLE
Build a single extension version

### PR DESCRIPTION
**Pull request by davidyuk**
depends on #941 
This would simplify switching to vue/cli and also speed up a default `build` script

@Liubov-crypto, please ensure that the Firefox extension behaving as before

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
FF extension:
Create a new wallet - pass 
Balances - pass 
Search tokens - pass 
Activity History - pass  
Sort by Date - pass 
Info about the transaction - pass
Copy wallet address - pass
Change currency - pass  
Change tokens - pass 
Send Tokens - pass, using QR - pass 
Connection with Jelly Swap - pass 
Send Tip - pass 
Send Tip - pass via Youtube/Twitter button - pass 
Retip - pass 
Register a name - pass 
Extend - pass 
Set name pointer - pass 
Set as default name - pass 
Generate invite link - pass 
Claim back invite link - failed  (fixed in pr #937 )
Top Up invite link - pass 
Settings: 
Change language - pass 
Security&Privacy - pass 
Change Network - failed  
Permission Settings - pass 
Remove account - pass 


Currency scrolling in the main menu/Tips tab/Tx history does not work:
https://user-images.githubusercontent.com/69896204/112863113-2d69e500-90bf-11eb-81f8-336f1a6acb0f.mov

In the new wallet, the inscription is shifted:
new wallet FF

Idk, if it's a bug, but should describe: name is pending - set name pointer option is available.

Got error when switching to the testnet, described in https://github.com/aeternity/superhero-wallet/issues/907#issuecomment-809553301

also remains #889 #849

**Comment by Liubov-crypto** [comment]
> > In the new wallet, the inscription is shifted
> 
> > Currency scrolling in the main menu/Tips tab/Tx history does not work
> 
> As I see, it works the same on the develop branch
> 
> > name is pending - set name pointer option is available
> 
> this is a bug, extracted to #946
> 
> are there any errors introduced in this PR?

only the bugs described above, but apparently, they are repeated in the development branch

**Review by kenodressel — COMMENTED** [review]
The code changes look simple enough. Why are the automated tests failing?

**Comment by davidyuk** [comment]
They are poor-written, we have to restart them several times to pass. The test scenarios are almost the same so I assume that tests are fine if one of GH Actions pipeline complete.

**Pull request merged**
