### PR TITLE
Remove minimum AENS name length limit

### PR DESCRIPTION
**Pull request by mradkov**

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
Tested, LGTM. 
I registered names of 9-10 characters. They are now at auction.

**Comment by mradkov** [comment]
> Tested, LGTM.
> I registered names of 9-10 characters. They are now at auction.

Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?

**Comment by Liubov-crypto** [comment]
> Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?

You are welcome! Every transaction went smoothly and I see my names in active auctions in the wallet. 
(I registered 3 names with web wallet, FF/Chrome extension on testnet.)

names auction

Btw, by registering the names, I spent a few ae tokens, but these transactions show up with zero sum in the Activity. Is this normal behavior?
activity

**Comment by mradkov** [comment]
> > Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?
> 
> You are welcome! Every transaction went smoothly and I see my names in active auctions in the wallet.
> (I registered 3 names with web wallet, FF/Chrome extension on testnet.)
> ...
> Btw, by registering the names, I spent a few ae tokens, but these transactions show up with zero sum in the Activity. Is this normal behavior?

The values should be present. 🤔

**Comment by Liubov-crypto** [comment]
> > > Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?
> > 
> > 
> > You are welcome! Every transaction went smoothly and I see my names in active auctions in the wallet.
> > (I registered 3 names with web wallet, FF/Chrome extension on testnet.)
> > ...
> > Btw, by registering the names, I spent a few ae tokens, but these transactions show up with zero sum in the Activity. Is this normal behavior?
> 
> The values should be present. 🤔

Should this case be logged as a bug?

These are the last transactions where I see the amounts that were debited:
https://testnet.aeternal.io/transactions/th_9AZvDPnN3wMAHZW5mxHVoM5RERajB6S2jqcZmzqJs48QGEirK
https://testnet.aeternal.io/transactions/th_2Ymmz11HAepcarpmeVUv4CWPqvRa9yWZvjwX2BfCPWQkeKbTwN
https://testnet.aeternal.io/transactions/th_2UT6xzJNLJS7CanLnTpnHyaFqiYfYgRk4GSWpVnQDmMptf9Ajc
https://testnet.aeternal.io/transactions/th_siVS4apVwe1JrT3o7srvio4JH2w8NzafoS4HiMW8Rp3DigAnz
https://testnet.aeternal.io/transactions/th_3fckUTrrRUJ9mwnnK7hiPLs7Gv3oV4zT3X9Aga6v9exiQjEPZ
https://testnet.aeternal.io/transactions/th_ktSt1j9xWE28JNidjBmfCBbbxnFAP1Xav5ppwtnoPzXqJmNL4

**Comment by mradkov** [comment]
> > > > Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?
> > > 
> > > 
> > > You are welcome! Every transaction went smoothly and I see my names in active auctions in the wallet.
> > > (I registered 3 names with web wallet, FF/Chrome extension on testnet.)
> > > ...
> > > Btw, by registering the names, I spent a few ae tokens, but these transactions show up with zero sum in the Activity. Is this normal behavior?
> > 
> > 
> > The values should be present. 🤔
> 
> Should this case be logged as a bug?
> 
> These are the last transactions where I see the amounts that were debited:
> https://testnet.aeternal.io/transactions/th_9AZvDPnN3wMAHZW5mxHVoM5RERajB6S2jqcZmzqJs48QGEirK
> https://testnet.aeternal.io/transactions/th_2Ymmz11HAepcarpmeVUv4CWPqvRa9yWZvjwX2BfCPWQkeKbTwN
> https://testnet.aeternal.io/transactions/th_2UT6xzJNLJS7CanLnTpnHyaFqiYfYgRk4GSWpVnQDmMptf9Ajc
> https://testnet.aeternal.io/transactions/th_siVS4apVwe1JrT3o7srvio4JH2w8NzafoS4HiMW8Rp3DigAnz
> https://testnet.aeternal.io/transactions/th_3fckUTrrRUJ9mwnnK7hiPLs7Gv3oV4zT3X9Aga6v9exiQjEPZ
> https://testnet.aeternal.io/transactions/th_ktSt1j9xWE28JNidjBmfCBbbxnFAP1Xav5ppwtnoPzXqJmNL4

I think this is a feature which needs to be specified and have the design adjusted. The transactions you've pointed out are getting the value in the form of TX fee - which we do not show in the transaction history on the screenshot.

So I do not consider this a bug, rather something to be improved visually.

**Comment by Liubov-crypto** [comment]
> > > > > Thank you. Did you got any problems while doing so, and are you able to see your active auctions in the wallet?
> > > > 
> > > > 
> > > > You are welcome! Every transaction went smoothly and I see my names in active auctions in the wallet.
> > > > (I registered 3 names with web wallet, FF/Chrome extension on testnet.)
> > > > ...
> > > > Btw, by registering the names, I spent a few ae tokens, but these transactions show up with zero sum in the Activity. Is this normal behavior?
> > > 
> > > 
> > > The values should be present. 🤔
> > 
> > 
> > Should this case be logged as a bug?
> > These are the last transactions where I see the amounts that were debited:
> > https://testnet.aeternal.io/transactions/th_9AZvDPnN3wMAHZW5mxHVoM5RERajB6S2jqcZmzqJs48QGEirK
> > https://testnet.aeternal.io/transactions/th_2Ymmz11HAepcarpmeVUv4CWPqvRa9yWZvjwX2BfCPWQkeKbTwN
> > https://testnet.aeternal.io/transactions/th_2UT6xzJNLJS7CanLnTpnHyaFqiYfYgRk4GSWpVnQDmMptf9Ajc
> > https://testnet.aeternal.io/transactions/th_siVS4apVwe1JrT3o7srvio4JH2w8NzafoS4HiMW8Rp3DigAnz
> > https://testnet.aeternal.io/transactions/th_3fckUTrrRUJ9mwnnK7hiPLs7Gv3oV4zT3X9Aga6v9exiQjEPZ
> > https://testnet.aeternal.io/transactions/th_ktSt1j9xWE28JNidjBmfCBbbxnFAP1Xav5ppwtnoPzXqJmNL4
> 
> I think this is a feature which needs to be specified and have the design adjusted. The transactions you've pointed out are getting the value in the form of TX fee - which we do not show in the transaction history on the screenshot.
> 
> So I do not consider this a bug, rather something to be improved visually.

ok, got it! Thank you! :)

**Pull request merged**
