### PR TITLE
chore: update SDK to 8.0.0

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by mradkov** [comment]
@Liubov-crypto is this well tested?

**Review by Liubov-crypto — COMMENTED** [review]
Web wallet (tested on the mainnet):
Create a new wallet - pass 
Login into the wallet - pass 
Activity History - pass 
 Sort by Date - pass 
 Info about the transaction - pass 
Copy wallet address - pass  
Change currency - pass 
Change tokens - pass +
Send ae tokens - pass, using QR - pass 
 Top up ae - pass  
Top up FT - pass 
Connection with Jelly Swap - no for the web wallet 
Send Tip - pass 
Claim Tip - pass 
Send Tip to HTTP (receive a warning) - pass 
Retip - failed
 Register a name - pass  
Extend - pass
Set name pointer - pass  (automatically for a new name) 
 Set as default name - pass 
Invite link:  
Generate invite link - pass 
Claim back invite link - pass 
Top Up invite link - pass 
Settings:
 Change language - pass 
 Security&Privacy - pass 
 Change Network - pass 
 Permission Settings - pass 
Remove account - pass 

Also remains #1059 #1079 

It is possible to create an invite link with FT (although this option has been canceled): 
generate link with FT tokens

Truncated search field: 
cropped line in search transactions

Registered names do not show up in the sub-accounts, I need to go to the names tab, click the name and the name becomes visible.

FT for some reason disappeared from the wallet, and after reloading the page it reappeared. 

Got this error when sending FT from one subaccount to another:
send FT from sub acc to acc
send ft from acc to acc 1

**Comment by Liubov-crypto** [comment]
Tested on the testnet:
The balance after the registration of the name remains the same. I think the name was not registered:

https://user-images.githubusercontent.com/69896204/118494912-4d1aa280-b72b-11eb-9dc8-6736201df459.mov

Got this error when trying to retip superhero:retip?id=26_v1
retip on the testnet
retip err test

Incorrect display of the name (should be aliensalreadyhere.chain:
strange name view

Maybe, it might make sense to shrink this image as the user has to go down to see the generated invite link:
штм дштл

TypeError in iframe wallet (https://test-wallet.aggregator.z52da5wt.xyz/): 
type error
type error1

Error in iframe wallet:
err tetsnet
Donate data field is empty:
donate data is empty

I was unable to set the name pointer to my middle name in the sub-account, although the transaction was successful.

**Comment by Liubov-crypto** [comment]
Got this error after sending a tip: 
send tip error

Claim amount is very small (should be bigger, at least 0.8 ae): 
claim

Got these errors after sending retip on the feed (maybe it is due maintaining?):
Безіменний 3
Безіменний 4
retip on te feed


The name is registered but does not appear in the wallet: bbbbbbbbbbbbbbbb.chain 

Voting - does not work with wallet testnet.
Meet - does not work with wallet testnet.

**Comment by Liubov-crypto** [comment]
Web wallet:
Balances - pass
Send ae - pass
Receive ae - pass
Tx history - pass
Sort by date - pass
Connection with Jelly Swap - no for the web wallet
Send tip - pass
Claim tip - pass (but very small amount)
Invite link - pass all transactions
Register name - pass 
Permisson setting - pass
Settings - pass

All send transactions are processed very slowly.
Name was registered but do not appear in the wallet: bbbbbbbbbbbbbbbb.chain 



On superhero UI:
Post without tipping - pass
Edit profile - pass
Retip on the feed - pass
Comment - pass
Send tip - pass
Change profile/back pic - pass
Pin to channel/unpin - pass
Tip on the feed - pass
Send tip on the feed - pass

Voting - don’t work with wallet (testnet)
Meet - don’t work with wallet (testnet)


FF/Chrome ext wallet:  
Generate new wallet - pass 
 Login into the wallet - pass  
Change currency - pass   
Copy address - pass  
Send/Withdraw ae, via scan pass 
 Receive ae- pass 
Connection with Jelly Swap - pass (connected, but the balance is displayed on the main network)
Send Tip - pass  
Send Tip to http - pass (receive a warning)  
Tip via Twitter/Youtube button - pass  
 Retip - pass (on sh ui)
 Claim Tip - pass  
Activity - pass, 
Sort by date - pass 
Transaction details - pass 
Names: 
Set name pointer - pass (tested with already registered names)  
Extend - pass (tested with already registered names)
 Set as default name - pass (tested with already registered names)
 Register name - pass  (but has not yet appeared in the wallet -MMMMMMMMMMM.chain)
Invite link: 
Create - pass  
Top up - pass 
 Claim back - pass

**Review by etharner — APPROVED** [review]

**Pull request merged**
