### PR TITLE
[SW-1187] Use last active Aeternity account for Aeternity protocol related features

### PR DESCRIPTION
**Pull request by subhod-i**

### CODE REVIEW

**Review by CedrikNikita — COMMENTED** [review]
Code changes look reasonable. But this should be carefully tested.

**Review by martinkaintas — APPROVED** [review]
LGTM

**Review by CedrikNikita — CHANGES_REQUESTED** [review]
In general, this approach is not enough, because our app will try to sign from the active account in some places, so we would need to change active account or sign with `fromAccount` option.
image

**Comment by subhod-i** [comment]
@peronczyk is looking into this. marking this as draft.

**Comment by subhod-i** [comment]
Closing this in favor of https://github.com/aeternity/superhero-wallet/pull/2284

**Pull request closed without merging**
