### PR TITLE
Release v0.8.0

### PR DESCRIPTION
**Pull request by etharner**

### CODE REVIEW

**Comment by kenodressel** [comment]
A thing i noticed is broken:

Expected Behavior:
- Click on Balances
- Select any token
- Click on receive
- Click on the back arrow at the top
- You land on the token screen you initially selected

Actual behavior:
- Click on Balances
- Select any token
- Click on receive
- Click on the back arrow at the top
**- You land on /payments
- Click back again
- You land on /account**

**Comment by Liubov-crypto** [comment]
Tested on a mobile (Android), Safari, FF, Chrome, and Brave browsers (FF/Chrome extensions + web wallet), LGTM:  
Create a new wallet - pass
Change tokens/currency - pass 
Send ae - pass 
Receive ae - pass 
Send FT - pass 
Receive FT - pass 
Balances view- pass 
Send via scan QR - pass 
AE/FT are displayed in Tx History - pass 
Send Tip - pass 
Claim tip - pass 
Tx history - pass 
Tx details - pass 
Invite link: create, top up, claim back - pass 
Register a name - pass 
Set name pointer - pass 
Set as default name - pass 
Extend - pass 
Settings - pass 
Networks - pass

**Review by kenodressel — APPROVED** [review]
lgtm

**Comment by Liubov-crypto** [comment]
Tested, LGTM. 

Create a new wallet - pass
Change tokens/currency - pass 
Send ae - pass 
Receive ae - pass 
Send FT - pass 
Receive FT - pass 
Balances view- pass 
Send via scan QR - pass 
AE/FT are displayed in Tx History (All/Sent/Received) - pass 
Send Tip - pass 
Claim tip - pass 
Tx history - pass 
Tx details - pass 
Invite link: create, top up, claim back - pass 
Register a name - pass 
Set name pointer - pass 
Set as default name - pass 
Extend - pass 
Settings - pass 
Networks - pass

**Pull request merged**
