### PR TITLE
feat: redirect only from /tip to /tips

### LINKED ISSUE #1220: Implement a redirect from /tip to /tips to fix Superhero utils

### PR DESCRIPTION
**Pull request by davidyuk**
based on https://github.com/aeternity/superhero-ui/blob/3ad2490571b7aa2c65a4e2fc56eab3464b5f40eb/src/router.js#L81-L84
supposed to fix #1220 
need to ensure that redirect works in Cordova

### CODE REVIEW

**Comment by davidyuk** [comment]
looks working for links like https://feature-redirect-tip-tips.wallet.z52da5wt.xyz/tip?url=http%3A%2F%2Fexample.com%2Farticle%3Fid%3D123123&amount=1.1&message=This%20is%20a%20test%20message%21%20http%3A%2F%2Fexample.com&x-success=https%3A%2F%2Ffeature-redirect-tip-tips.wallet.z52da5wt.xyz%2Fartifacts%2Fdeeplink-test.html%3Fresult%3Dsuccess&x-cancel=https%3A%2F%2Ffeature-redirect-tip-tips.wallet.z52da5wt.xyz%2Fartifacts%2Fdeeplink-test.html%3Fresult%3Dcancel

**Comment by CedrikNikita** [comment]
This won't redirect in this case, 
tip/claim to the tips/claim

**Comment by davidyuk** [comment]
we are not using `tip/claim` anywhere, so we don't need to care about it

**Comment by etharner** [comment]
> we are not using `tip/claim` anywhere, so we don't need to care about it

Agree, let's merge this on top of #1233

**Review by etharner — APPROVED** [review]

**Pull request merged**
