### PR TITLE
fix: open cancel callback urls in the same tab

### PR DESCRIPTION
**Pull request by pstachel**

### CODE REVIEW

**Review by CedrikNikita — COMMENTED** [review]
why did you make it opened in the same tab only on not success?

**Review by CedrikNikita — CHANGES_REQUESTED** [review]
This approach doesn't work in cordova version.

**Review by CedrikNikita — COMMENTED** [review]
This PR should be also rebased on the develop.

**Review by CedrikNikita — COMMENTED** [review]
image

If the url would be without protocol.

**Review by davidyuk — APPROVED** [review]
code changes looks fine, but squash commits in the branch or use squash merging

**Comment by kenodressel** [comment]
Apparently not working on android version @kenodressel will test :)

**Pull request merged**
