### PR TITLE
Update TokenAmount

### LINKED ISSUE #1176: Do not show a conversion rate to dollar on a fake AE
**Describe the bug**

Currently the wallet is showing a conversion to dollar for a aex9 contract with the symbol "AE". This makes the token look incredibly similar to the real ae.

**Screenshots**

Half of them are real AE, the other token transactions.
image

### LINKED ISSUE #1192: Realign symbols & balances
**For AE SpendTx & AE Balance & AEX9 Transfer with known Boding Curve & AEX9 Balances with bonding curve:** 
0 AE = (0.00€)
0.00001 AE = (<0.01€)
1 AE = (≈0.09€)

**For all other TX types, show their type:**
contractCall
contractCreate
namePreClaim
nameClaim
nameBid
nameUpdate

**For AEX9 Transfer or Balance without bonding curve (all of them atm):**
Show nothing.

### PR DESCRIPTION
**Pull request by imollov**
fixes #1176, closes #1192

### CODE REVIEW

**Comment by kenodressel** [comment]
The fiat is still shown in the token list:
image

Also in the detail overview:
image

A weird byproduct is that we now see the tx type, but not for all tx:
image

**Review by kenodressel — CHANGES_REQUESTED** [review]
I still see a `ContractCreateTx` in my list.

**Comment by imollov** [comment]
> I still see a `ContractCreateTx` in my list.

Tx types are displayed by design, when fiat converted amount is >= 0.01.

After this PR, when interacting with AEX9 tokens (`ContractCall`) - nothing is displayed as descriptive text.

**Review by kenodressel — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
Tested, in general LGTM.

**Pull request merged**
