### PR TITLE
Fix blank screen after splash on iOS

### LINKED ISSUE #833: Blank screen after splash on iOS below 14
Introduced in PR #525

### PR DESCRIPTION
**Pull request by imollov**
fixes #833

QA:
* QR code read related functionality must be tested well on all platforms

### CODE REVIEW

**Review by davidyuk — COMMENTED** [review]
The black screen was because of es features of `@zxing/library` or what?

**Comment by imollov** [comment]
> The black screen was because of es features of `@zxing/library` or what?

Probably but can't tell for sure because no errors are logged. 

In any case - not importing a browser-only package on mobile must be beneficial, right?

**Comment by mradkov** [comment]
Can you adapt the e2e test to the changes as well?

**Comment by davidyuk** [comment]
> Probably but can't tell for sure because no errors are logged.

Have you tried to connect Safari/Chrome debugger to the mobile app built in develop mode? You should see the exception in the console then.

> In any case - not importing a browser-only package on mobile must be beneficial, right?

Agree. In general, I think would be best to split this component into two for web and Cordova because scanning approaches are too different.

**Comment by imollov** [comment]
> > Probably but can't tell for sure because no errors are logged.
> 
> Have you tried to connect Safari/Chrome debugger to the mobile app built in develop mode? You should see the exception in the console then.
> 
> > In any case - not importing a browser-only package on mobile must be beneficial, right?
> 
> Agree. In general, I think would be best to split this component into two for web and Cordova because scanning approaches are too different.

Here's the exception causing the black screen:
Screenshot 2021-02-22 at 14 59 50

And an issue to refactor as suggested: #837

**Review by davidyuk — APPROVED** [review]

**Comment by davidyuk** [comment]
Actually, this is a workaround. We won't be able to use QR code scanner in a web version on iOS below 14:



this is a simulator, iOS 12.4, iPhone 7

**Review by mradkov — APPROVED** [review]
Let us fix the actual app problems, and we can resolve the web safari issue separately. Feel free to merge.

**Pull request merged**
