### PR TITLE
Fix names and fungible tokens usage with subaccounts

### LINKED ISSUE #907: Error when switching networks
> Screenshot 2021-03-17 at 16 09 53
...

Now I got this error when switched between networks.

_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/883#issuecomment-801130363_

tested on develop 226adef

quick findings:
* to reproduce you must have a ft transfer transaction
* seems like the available ft tokens in the state are not in sync with transactions for a quick moment after switching networks

related to #905

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Error when switching to balances:
error switching to balances
err sw

White text on white background:
white on white text

Got this error when registering a name on sub-accounts:
registering a name
err with name

also remains #1003 

giving up
givinh up 2


After the payment transaction, the name in the account was changed by itself, although by default I set a different name.

**Comment by Liubov-crypto** [comment]
Error when registering a name in a sub-account (name was registered at 2 attempt):
error when registering a name in sub-account
cons1

Error when switching to Balances tab:
error when switching to balances

Send FT in the Test network - transaction takes a long time to process (about 2 min).

Visual bug in web wallet (test network):
visual bug in web wallet

FT transactions are not shown in TX history. Only AE token transactions are visible (testnet).

Sub-accounts (tested in the mainnet/testnet): 
Send ae - pass
Receive ae - pass
Send FT - pass
Receive FT - pass 
Balances view- pass
Send via scan QR - pass
Send Tip - pass
Claim tip - pass (but comes a very small amount 1-18ае)
Tx history - pass
Tx details - pass
Invite link: create, top-up, claim back - pass
Register a name - pass
Settings - pass
Networks - pass

**Comment by Liubov-crypto** [comment]
Visual bug in web wallet (test network):
visual bug in web wallet

fixed by #1082

**Comment by Liubov-crypto** [comment]
Sub-accounts (tested in the mainnet/testnet, webwallet/extension):
Search tokens - pass
Change tokens/currency - pass
Change sub-account info - pass
Send ae - pass 
Receive ae - pass 
Send FT - pass 
Receive FT - pass 
Balances view- pass 
Send via scan QR - pass 
Send Tip - pass 
Claim tip - pass 
Tx history - pass 
Tx details - pass 
Invite link: create, top up, claim back - pass 
Register a name - pass 
Set name pointer - pass 
Extend - pass 
Settings - pass 
Networks - pass 

FT transactions are not shown in Sent/Received history (testnet). Only AE token transactions are visible (testnet).

Idk, if this issue matches this PR: 
leave wallet for a while:
leave wallet for a while
cons

**Review by etharner — APPROVED** [review]

**Pull request merged**
