### PR TITLE
Cleanup global styles

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Review by CedrikNikita — APPROVED** [review]
The changes look reasonable, but some of them a little out of place.

**Review by Liubov-crypto — COMMENTED** [review]
Tested - looks good. 

Note: not all fields are translated into Chinese (Tokens, Permissions settings). This bug is also on the developer version.

**Comment by mradkov** [comment]
> Tested - looks good.
> 
> Note: not all fields are translated into Chinese (Tokens, Permissions settings). This bug is also on the developer version.

I wouldn't say it's a bug, it's just that we lack translations for all of the text on the wallet.

**Review by mradkov — APPROVED** [review]
Changes look good, though they seem to be touching lots of areas in the wallet. Let's maybe merge it after we finalize the other smaller PRs?

**Comment by davidyuk** [comment]
Actually, the broadest change is to renaming `common` to `styles` that modifies a lot of components but it should be easy to rebase on top of that.

**Pull request merged**
