### PR TITLE
[SW-985] refactor: reduce accounts color saturation

### PR DESCRIPTION
**Pull request by subhod-i**

### CODE REVIEW

**Comment by subhod-i** [comment]
LHS is the new color selection from this PR. RHS is the existing color.
Screenshot 2023-06-29 at 4 40 45 PM
Screenshot 2023-06-29 at 4 41 30 PM

Screenshot 2023-06-29 at 4 40 36 PM

**Comment by Liubov-crypto** [comment]
Almost imperceptibly that the color saturation has changed, but maybe these are my screen brightness settings:

https://github.com/aeternity/superhero-wallet/assets/69896204/7c0f177f-4236-425f-8677-ac7d82c6e2a4

**Comment by subhod-i** [comment]
> Almost imperceptibly that the color saturation has changed, but maybe these are my screen brightness settings:
> 
>  2023-06-29.5.21.52.mov

Thanks. We have reduce the saturation a bit more. Please re run the tests now

**Comment by subhod-i** [comment]
Reduced color saturation on the left

Screenshot 2023-06-30 at 12 43 12 PM
Screenshot 2023-06-30 at 12 43 19 PM
Screenshot 2023-06-30 at 12 52 53 PM

**Comment by Liubov-crypto** [comment]
Now it's better, LGTM.

**Review by peronczyk — APPROVED** [review]

**Review by pstachel — APPROVED** [review]

**Pull request merged**
