### PR TITLE
Release 0.5.6

### PR DESCRIPTION
**Pull request by mradkov**

### CODE REVIEW

**Review by davidyuk — APPROVED** [review]
In general looks good

**Comment by Liubov-crypto** [comment]
Web wallet / FF ext /Chrome  ext:
Generate new wallet - pass/ pass/ pass
 Login into the wallet - pass/ pass/ pass
 Change tokens - pass/ pass/ pass
 Change currency - pass/ pass/ pass
Copy address - pass/ pass/ pass
 Send Tip - pass/ pass/ pass
 Send Tip to HTTP - pass (receive a warning)/ pass/ pass
Tip via Twitter/Youtube button - no for web wallet/pass/ pass
Retip - pass/ pass/ pass
Claim Tip - pass/ pass/ pass 
Top Up with ae tokens - pass/ pass/ pass 
 Top Up with FT- pass/ pass/ pass 
Connection with Jelly Swap -no for web wallet/ pass/ pass 
Withdraw (Send) - pass, via Scan QR code - pass/ pass/ pass 
Activity - pass, sort by date - pass/ pass/ pass(transactions are displayed with a delay)  
Tokens: search - pass/ pass/ pass
 Send - pass/ pass/ pass
Receive - pass/ pass/ pass
 Names:
 Set name pointer - pass/ pass/ pass
Extend - pass/ pass/ pass
 Set as default name - pass/ pass/ pass
Register name - pass/ pass/ pass (in the testnet) 
 Invite link:  
Create - pass/ pass/ pass
 Top up - pass/ pass/ pass
Claim back - pass/ pass/ pass
Settings: 
Language - pass/ pass/ pass 
Security&Privacy - pass/ pass/ pass
Networks - pass/ pass/ pass
 Permission Settings - pass/ pass/ pass
Remove account - pass/ pass/ pass

Error with the compiler in FF and Chrome extensions:
error when claim tokens  tokens were claimed
switched btw nets

Error when creating Invite link with FT :
inv link with FT
(it might be good to create such an option for users)

The ae tokens amount in the wallet(Chrome ext) changed randomly after claim transactions (696.42--->698.42--->696.42)

Search FT- tokens are displayed that do not contain search letters:
ww

**Comment by mradkov** [comment]
> Web wallet / FF ext /Chrome  ext:
> Generate new wallet - pass/ pass/ pass
>  Login into the wallet - pass/ pass/ pass
>  Change tokens - pass/ pass/ pass
>  Change currency - pass/ pass/ pass
> Copy address - pass/ pass/ pass
>  Send Tip - pass/ pass/ pass
>  Send Tip to HTTP - pass (receive a warning)/ pass/ pass
> Tip via Twitter/Youtube button - no for web wallet/pass/ pass
> Retip - pass/ pass/ pass
> Claim Tip - pass/ pass/ pass
> Top Up with ae tokens - pass/ pass/ pass
>  Top Up with FT- pass/ pass/ pass
> Connection with Jelly Swap -no for web wallet/ pass/ pass
> Withdraw (Send) - pass, via Scan QR code - pass/ pass/ pass
> Activity - pass, sort by date - pass/ pass/ pass(transactions are displayed with a delay)
> Tokens: search - pass/ pass/ pass
>  Send - pass/ pass/ pass
> Receive - pass/ pass/ pass
>  Names:
>  Set name pointer - pass/ pass/ pass
> Extend - pass/ pass/ pass
>  Set as default name - pass/ pass/ pass
> Register name - pass/ pass/ pass (in the testnet)
>  Invite link: 
> Create - pass/ pass/ pass
>  Top up - pass/ pass/ pass
> Claim back - pass/ pass/ pass
> Settings: 
> Language - pass/ pass/ pass 
> Security&Privacy - pass/ pass/ pass
> Networks - pass/ pass/ pass
>  Permission Settings - pass/ pass/ pass
> Remove account - pass/ pass/ pass
> 
> Error with the compiler in FF and Chrome extensions:
> error when claim tokens tokens were claimed
> switched btw nets
> 
> Error when creating Invite link with FT :
> inv link with FT
> (it might be good to create such an option for users)
> 
> The ae tokens amount in the wallet(Chrome ext) changed randomly after claim transactions (696.42--->698.42--->696.42)
> 
> Search FT- tokens are displayed that do not contain search letters:
> ww

Can you create issues about those? I don't think they are introduced by this release, so we can resolve them separately without blocking the release.

**Comment by Liubov-crypto** [comment]
> > Web wallet / FF ext /Chrome >  ext:
> > Generate new wallet - pass/ pass/ pass
> >  > Login into the wallet - pass/ pass/ pass
> >  > Change tokens - pass/ pass/ pass
> >  > Change currency - pass/ pass/ pass
> > Copy address - pass/ pass/ pass
> >  > Send Tip - pass/ pass/ pass
> >  > Send Tip to HTTP - pass (receive a warning)/ pass/ pass
> > Tip via Twitter/Youtube button - no for web wallet/pass/ pass
> > Retip - pass/ pass/ pass
> > Claim Tip - pass/ pass/ pass
> > Top Up with ae tokens - pass/ pass/ pass
> >  > Top Up with FT- pass/ pass/ pass
> > Connection with Jelly Swap -no for web wallet/ pass/ pass
> > Withdraw (Send) - pass, via Scan QR code - pass/ pass/ pass
> > Activity - pass, sort by date - pass/ pass/ pass(transactions are displayed with a delay)
> > Tokens: search - pass/ pass/ pass
> >  > Send - pass/ pass/ pass
> > Receive - pass/ pass/ pass
> >  > Names:
> >  > Set name pointer - pass/ pass/ pass
> > Extend - pass/ pass/ pass
> >  > Set as default name - pass/ pass/ pass
> > Register name - pass/ pass/ pass (in the testnet)
> >  > Invite link: > 
> > Create - pass/ pass/ pass
> >  > Top up - pass/ pass/ pass
> > Claim back - pass/ pass/ pass
> > Settings: > 
> > Language - pass/ pass/ pass > 
> > Security&Privacy - pass/ pass/ pass
> > Networks - pass/ pass/ pass
> >  > Permission Settings - pass/ pass/ pass
> > Remove account - pass/ pass/ pass
> > Error with the compiler in FF and Chrome extensions:
> > error when claim tokens tokens were claimed
> > switched btw nets
> > Error when creating Invite link with FT :
> > inv link with FT
> > (it might be good to create such an option for users)
> > The ae tokens amount in the wallet(Chrome ext) changed randomly after claim transactions (696.42--->698.42--->696.42)
> > Search FT- tokens are displayed that do not contain search letters:
> > ww
> 
> Can you create issues about those? I don't think they are introduced by this release, so we can resolve them separately without blocking the release.

sure, here they are: https://github.com/aeternity/superhero-wallet/issues/846
https://github.com/aeternity/superhero-wallet/issues/847
https://github.com/aeternity/superhero-wallet/issues/849
https://github.com/aeternity/superhero-wallet/issues/804

**Review by imollov — APPROVED** [review]
LGTM

**Pull request merged**
