### PR TITLE
Drop comment deeplink

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by mradkov** [comment]
Why drop it?

**Comment by davidyuk** [comment]
A separate deeplink for comments won't be needed by reusing [backendAuthMixin](https://github.com/aeternity/superhero-ui/blob/cb50c3ce1f1a5b645a8b8e4bda71cfa7ffaaf88a/src/utils/backendAuthMixin.js) on superhero-ui side. I'm planning to finish that later.

**Comment by mradkov** [comment]
@davidyuk what is the state of this PR?

**Comment by davidyuk** [comment]
The comment deeplink is still used on superhero-ui side. But I didn't change my mind about unnecessarily of that.

**Comment by mradkov** [comment]
Closing this as its stale. Lets reopen in the future if needed.

**Comment by davidyuk** [comment]
@mradkov should I put my code into issues to don't lose it?

**Pull request closed without merging**
