### PR TITLE
Background refactoring

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
Chrome ext : 
Balances -  pass 
Send FT - pass 
Tx history - pass 
Sort by date - pass 
Info about transaction - failed 
Change currency - pass 
Change tokens - pass 
Copy wallet address - pass 
Send Tip via Youtube/Twitter button - pass 
Create Invite link - pass 
Top up - pass 
Claim back invite link - failed 
Payments (Send tokens) -  pass 
Register name- pass 
Extend name - pass 
Set as default - pass 
Set name pointer - pass 
Connection with Jelly Swap - pass 
Settings - pass.
Permission Settings - pass 

Web wallet: 
Balances - pass 
Search tokens - pass 
Activity History - pass 
Sort by Date - pass 
Info about transaction - failed 
Copy wallet address - pass 
Change currency - pass 
Change tokens - pass 
Send Tokens - pass, using QR - pass 
Send Tip - pass 
Retip - pass 
Register a name - pass 
Extend - pass 
Set name pointer - pass 
Set as default name - pass 
Generate invite link - pass 
Claim back invite link - failed  
Top Up invite link - pass 
Settings: 
Change language - pass 
Security&Privacy - pass 
Change Network - pass 
Permission Settings - pass 
Remove account - pass 

I was unable to enter the FF extension: 



Got this error on testnet when clicking on the name: 

testname network

I need to reload the sh page to see the correct balances (in Brave browser): 


If I click on a transaction I don't see its details, the field is inactive (also on the development branch).

.chain name is displayed as Fellow superhero on sh feed.

**Comment by davidyuk** [comment]
@Liubov-crypto Please compare it with the list of bugs in the current develop branch and list only things that get worse.

**Comment by Liubov-crypto** [comment]
This error is not repeated at the development branch.

Got this error on testnet when clicking on the name: 

testname network

**Comment by davidyuk** [comment]
I forgot to reinit middleware on network change, the last bug should be fixed now.

**Review by mradkov — APPROVED** [review]
Code changes look good

**Pull request merged**
