### PR TITLE
chore(release): 0.9.11

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Comment by csiarab** [comment]
I was sending a tip and the pending state did not have any labels
εικόνα

**Comment by Liubov-crypto** [comment]
Can't generate an invite link on the testnet :

https://user-images.githubusercontent.com/69896204/184120956-597cb5d3-f64b-4a4e-becb-4ff361786319.mov

**Comment by Liubov-crypto** [comment]
Got this error when switched between networks   —v3/transactions/th_twcEB69M14pEkZcTcbDavZE9z6ZWdwu5mf7vA1q4GyG12eNoX error: Transaction not found 
switch between networks

**Comment by Liubov-crypto** [comment]
> Can't generate an invite link on the testnet :
> 
>  2022-08-11.1.10.49.mov

Retested, now works for me.

**Comment by Liubov-crypto** [comment]
Drop-down menu in All transactions tab: 
vis bug

**Comment by Liubov-crypto** [comment]
It seems to me that it would be better to show the user transactions with a pooled token on the page of this token. What do you think @paolomolo? 

allow tok ae
allow tok 2

**Comment by Liubov-crypto** [comment]
Create a new wallet - pass 
Verify Seed phrase-pass 
Change tokens/currency - pass 
Send ae - pass
 Receive ae - pass 
Send FT - pass
 Receive FT - pass
 Balances view- pass 
Send via scan QR - pass
 AE/FT is displayed in Tx History (All/Sent/Received) - pass
 Send Tip - pass
 Claim tip -pass 
Tx history - pass 
Tx details - pass 
Invite link: create - pass 
 top up -pass 
claim back - pass
 Register a name - pass (in testnet )
Set name pointer - pass  
Set as default name - pass
 Extend - pass 
Settings - pass
Permission settings - pass 
Networks - pass

Buy AE - I haven’t tested

The web wallet is not connected with superhero.com. - the same on dev version.

DEX:
Swap - pass
Allow token - pass
Add liquidity - pass
Remove liquidity - pass

**Review by Liubov-crypto — COMMENTED** [review]
In general LGTM.

**Comment by Liubov-crypto** [comment]
> artifacts

Retested, LGTM.

**Review by kenodressel — APPROVED** [review]

**Pull request merged**
