### PR TITLE
Fix "Invalid date" of pending transactions, and refactoring

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Review by CedrikNikita — APPROVED** [review]
Changes look reasonable

**Comment by Liubov-crypto** [comment]
When I tested this PR, I encountered an error in the FF extension but did not come across this error in a Chrome extension or web wallet. 
I send a tip on Youtube via the Youtube button, transactions in my wallet are marked as pending:

er in ff

While I see the same transaction in Chrome extension as sent:
FF extension - pending:
ff sent1
Chrome extension - sent:
brave sent

When I send tip I got this error in the web wallet: 

error on web

and in FF extension: 

eror in FF when sending tip

**Comment by davidyuk** [comment]
@Liubov-crypto this PR was merged, so please move it to a new issue to don't lose it.

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto this PR was merged, so please move it to a new issue to don't lose it.

done, moved to #695

**Pull request merged**
