### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by etharner**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Web wallet:  
Generate new wallet  - pass
Login into the wallet - pass  
Links in the Terms of Use lead to the desired pages - pass
Change tokens - pass  
Change currency - pass  
Copy address - pass 
Balances: 
Tokens search - pass  
Send - pass 
 Receive - pass 
 Send Tip - pass  
Send Tip to http - pass (receive a warning)
 Retip - pass  
Top Up ae tokens - pass  
Top Up FT- pass  
Send FT - pass
 Connection with Jelly Swap -no for web wallet 
Withdraw (Send) - pass, via Scan QR code - pass 
Tx History -  pass
Sort by date - pass  (transactions with FT (receive) are displayed with a delay)
Transaction details - pass
Names:
 Set name pointer - pass (set automatically for new names)
 Extend - pass 
Set as default name - pass 
 Register a name - pass 
Invite link:
 Create - pass  
Top up - pass  
Claim back - pass
Settings:
 Language - pass  
Security&Privacy - pass  
Networks - pass 
Permission Settings - pass 
Remove account - pass 
Report a bug - pass

When scrolling the drop-down menu with currencies, the field with transactions is also scrolled: 
https://user-images.githubusercontent.com/69896204/113877700-a05f1400-97c1-11eb-80b5-671c1f201cff.mov

If the URL is long, then it is truncated:
cropped url

Got this error when registering name (Name has been registered):
error when registering a name
err when reg a name

Cropped elements (Latin numbers) in Privacy Policy (mentioned in #872 comments):
cropped elements

also remains #849 #907 #953 #847 #946

**Review by Liubov-crypto — COMMENTED** [review]
FF/Chrome extension:
Generate new wallet - pass
Open external links in the proper way - pass 
 Login into the wallet - pass 
 Change tokens - pass 
Change currency - pass  
 Copy wallet address - pass 
Balances:  
Tokens: search - pass 
Send ae - pass 
 Receive ae - pass
Send Tip - pass 
 Send Tip to http - pass (receive a warning)
 Tip via Twitter/Youtube button - pass 
 Retip - pass 
Claim Tip - pass 
 Top Up ae tokens - pass 
 Top Up FT- pass  
Send FT - pass 
 Connection with Jelly Swap - pass 
 Withdraw (Send) - pass, via Scan QR code - pass  
 Activity - pass
Sort by date - pass 
Transaction details - pass 
Names: 
Set name pointer - pass (set automatically for new names)
 Extend - pass 
Set as default name - pass  
Register name - pass (in the testnet/mainnet)
Invite link: 
Create - pass 
 Top up - pass 
Claim back - pass
Settings: 
Language - pass 
 Security&Privacy - pass 
 Networks - pass  
 Permission Settings - pass  
Remove account - pass 

The scroller with currencies does not work in the dropdown menu (FF extension) (mentioned in https://github.com/aeternity/superhero-wallet/pull/872#issuecomment-808351121)
https://user-images.githubusercontent.com/69896204/112656860-7a00b680-8e5a-11eb-9ae2-a313b91a1f81.mov

Red borderline in FF extension:
red borderline in FF extension

FT for some reason is not displayed in Received transactions only in Sent.

**Comment by Liubov-crypto** [comment]
Android mobile browser:
Generate new wallet - pass 
Login into the wallet - pass  
Links in the Terms of Use lead to the desired pages - pass 
Change tokens - pass  
Change currency - pass  
Copy address - pass 
Balances: 
Tokens search - pass 
Send - pass 
 Receive - pass 
 Send Tip - pass  
Send Tip to HTTP - pass (receive a warning) 
 Retip - pass  
Top Up ae tokens - pass  
Top Up FT- pass
Send FT - pass 
 Connection with Jelly Swap -no for web wallet 
Withdraw (Send) - pass, via Scan QR code - pass 
Tx History -  pass 
Sort by date - pass  
Transaction details - pass 
Names:
 Set name pointer - pass (set automatically for new names) 
 Extend - pass  
Set as default name - pass 
 Register a name - pass (in the testnet)
Invite link:
 Create - pass  
Top up - pass  
Claim back - pass
Settings:
 Language - pass  
Security&Privacy - pass  
Networks - pass 
Permission Settings - pass 
Remove account - pass 
Report a bug - pass 

Cropped elements (Latin numbers) in Privacy Policy (mentioned in #872 comments).
FT for some reason is not displayed in Received transactions only in Sent.

also remains #907 #946

**Review by davidyuk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
If the list of names is long, then the last .chain name is truncated a little:
the last name is cutted

**Pull request merged**
