### PR TITLE
chore(release): 0.9.10

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Do we decide to hide some values?
ae tok

If the transaction is being processed, then the token will appear in the list of transactions of tokens to which it does not belong. or this is ok? 
pend

send

p.s. will continue my tests tomorrow

**Comment by Liubov-crypto** [comment]
if I click on the 6 WTT token and view the details, I will see the following (the same on dev version):
6 wttt

Names tab: 
names tab

Set name pointer error:
set name poiner error

waiting for name to register: 
network request failed
err

**Comment by Liubov-crypto** [comment]
Web wallet:
Create a new wallet - pass
Verify Seed phrase-pass
Change tokens/currency - pass
Send ae - pass
Receive ae - pass
Send FT - pass  
Receive FT - pass
Balances view- wrong balance for some tokens
Send via scan QR - pass
AE/FT is displayed in Tx History (All/Sent/Received) - pass
Send Tip - pass
Claim tip -pass
Tx history - pass
Tx details - pass
Invite link: create - pass
top up -pass
claim back - pass
Register a name - pass 
Set name pointer - pass but failed in some cases
Set as default name - pass
Extend - pass
Settings - pass
Networks - pass

The new name - make default button is absent. - the same on dev version. 

Not all names have a Make default button, in many, it is missing. - the same on dev version. 

Web wallet is not connected with superhero.com. - the same on dev version. 

Buy AE - haven’t tested

During testing, I noticed that the balance of tokens is displayed incorrectly after sending tokens to another address, for example: 

I had 142.7 ae - sent 1.1 = should be 141.6 ae — I have 141.59 ae in fact 

I had 700 Davidyuk - sent 1.1 = should be  698,9 Dav —  I have 699 IN FACT 

The same issue on dev version #1505

**Comment by Liubov-crypto** [comment]
tip icon shifted on twitter: 
tip

Permission settings - not working on superhero.com 

While the transaction of sending tokens was being processed, this pop-up constantly popped up:
pop up

FF/Chrome Extensions:
Create a new wallet - pass
Verify Seed phrase-pass
Change tokens/currency - pass
Send ae - pass
Receive ae - pass
Send FT - pass
Receive FT - pass
Balances view- wrong  balance for some tokens 
Send via scan QR - pass
AE/FT is displayed in Tx History (All/Sent/Received) - pass
Send Tip - pass
Send Tip via Twitter tip button - pass
Claim tip - pass
Tx history -pass
Tx details - pass
Invite link: create - pass
top up -pass
claim back - pass
Register a name - pass
Set name pointer - pass
Set as default name - pass
Extend - pass
Settings - pass
Permission Settings - not working with [superhero.com](http://superhero.com/) 
Networks - pass

**Comment by CedrikNikita** [comment]
> While the transaction of sending tokens was being processed, this pop-up constantly popped up: pop up

fixed

**Review by kenodressel — APPROVED** [review]
love all the new tests!

**Comment by onvisions** [comment]
I found the following problems: 

1. modals and popups are displayed below the top nav bar.
image
image

2. When placing bid for .chain name it took more than 5 mins. to see my bid in the Bid History.

**Comment by Liubov-crypto** [comment]
Set name pointer, when the name registration transaction is still pending: 
set name pointer

if I click on the 6 WTT token and view the details, I will see the following (the same on dev version):
6 wttt

Names tab: 
names tab

During testing, I noticed that the balance of tokens is displayed incorrectly after sending tokens to another address, for example:

I had 690.70 Davidyuk - sent 1.1 = should be 689,6 Dav — I have 689,5 IN FACT

The same issue on dev version https://github.com/aeternity/superhero-wallet/issues/1505

pop up in names/invite link is cropped:
pop up names

Web wallet:
Create a new wallet - pass
Verify Seed phrase-pass
Change tokens/currency - pass
Send ae - pass
Receive ae - pass
Send FT - pass
Receive FT - pass
Balances view- wrong balance for some tokens
Send via scan QR - pass
AE/FT is displayed in Tx History (All/Sent/Received) - pass
Send Tip - pass
Claim tip -pass
Tx history - pass
Tx details - pass
Invite link: create - pass
top up -pass
claim back - pass
Register a name - pass
Set name pointer - pass but failed in some cases
Set as default name - pass
Extend - pass
Settings - pass
Networks - pass

The new name - make default button is absent. - the same on dev version.

Not all names have a Make default button, in many, it is missing. - the same on dev version.

Web wallet is not connected with superhero.com. - the same on dev version.

Buy AE - haven’t tested

**Comment by Liubov-crypto** [comment]
tip icon shifted on twitter: 
tip

Permission settings - not working on superhero.com 

FF/Chrome Extensions:
Create a new wallet - pass
Verify Seed phrase-pass
Change tokens/currency - pass
Send ae - pass
Receive ae - pass
Send FT - pass
Receive FT - pass
Balances view- wrong balance for some tokens
Send via scan QR - pass
AE/FT is displayed in Tx History (All/Sent/Received) - pass
Send Tip - pass
Send Tip via Twitter tip button - pass
Claim tip - pass
Tx history -pass
Tx details - pass
Invite link: create - pass
top up -pass
claim back - pass
Register a name - pass
Set name pointer - pass
Set as default name - pass
Extend - pass
Settings - pass
Permission Settings - not working with [superhero.com](http://superhero.com/)
Networks - pass

 after the name pointer is set, the make default button does not appear in some names, and they cannot be applied, they have only 2 buttons set pointer and autoextend.

**Comment by Liubov-crypto** [comment]
approx icon: 
approx

Web wallet: 
Create a new wallet - pass
 Verify Seed phrase-pass
 Change tokens/currency - pass
 Send ae - pass 
Receive ae - pass
 Send FT - pass 
Receive FT - pass
 Balances view- pass 
Send via scan QR - pass
 AE/FT is displayed in Tx History (All/Sent/Received) - pass 
Send Tip - pass
 Claim tip -pass
 Tx history - pass
 Tx details - pass
Invite link: create - pass
 top up -pass 
claim back - pass
 Register a name - pass
 Set name pointer - pass  
Set as default name - pass
 Extend - pass
 Settings - pass
 Networks - pass


The new name - make default button is absent. - the same on dev version.
Not all names have a Make default button, in many, it is missing. - the same on dev version.
Web wallet is not connected with superhero.com. - the same on dev version.
Buy AE - haven’t tested

pending transactions view: 
тр
тип
тип 1
тип 2

**Comment by Liubov-crypto** [comment]
FF/Chrome Extensions:
Create a new wallet - pass
Verify Seed phrase-pass
Change tokens/currency - pass
Send ae - pass
Receive ae - pass
Send FT - pass
Receive FT - pass
Balances view- pass 
Send via scan QR - pass
AE/FT is displayed in Tx History (All/Sent/Received) - pass
Send Tip - pass
Send Tip via Twitter tip button - pass
Claim tip - pass
Tx history -pass
Tx details - pass
Invite link: create - pass
top up -pass 
claim back - pass 
Register a name - pass
Set name pointer - pass
Set as default name - pass
Extend - pass
Settings - pass
Permission Settings - pass
Networks - pass

The balance of some tokens (Davidyuk) is updated with a long delay. 
The names after registration appear in the wallet with a long delay

**Pull request merged**
