### PR TITLE
fix(transaction-overview): use correct label for a contract call

### PR DESCRIPTION
**Pull request by CedrikNikita**
missed in https://github.com/aeternity/superhero-wallet/pull/2136

### CODE REVIEW

**Review by pstachel — APPROVED** [review]

**Review by konradodo — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
LGTM. This pr has been fixed existing issue with labels. 

On some screenshots, the "smart" prefix is present. I suggest fixing this in a separate pr.

**Comment by onvisions** [comment]
I was asked by @CedrikNikita to provide my opinion about this issue from UX perspective. The question was should we also update the transaction type labels in such a way that "Contract call" becomes "Smart contract call". In short "No" because we are striving for having the labels text as short as possible. 
So my suggestion for consistency update will be the following:

1. Use "Smart contract" for the text under the identicon and above the smart contract address (see screenshot below);
2. Continue to use just "Contract call" (NOT "Smart contract call").
image

**Comment by CharisSiarampalis** [comment]
Lgtm

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by CharisSiarampalis** [comment]
Lgtm

**Pull request merged**
