### PR TITLE
fix(tab-bar): color home button area on iOS

### PR DESCRIPTION
**Pull request by davidyuk**
Before

Screenshot 2021-04-22 at 20 41 52

After

Screenshot 2021-04-22 at 20 39 18

### CODE REVIEW

**Comment by onvisions** [comment]
> 
> 
> Before
> 
> Screenshot 2021-04-22 at 20 41 52
> 
> After
> 
> Screenshot 2021-04-22 at 20 39 18
Suggested changes definitely make the UI look better than before. However I would suggest getting rid of the left, right and bottom menu borders for iOS devices. Because of the specifics of the device viewport it will look better (from visual perspective). Isn't it possible to have this approach applied for iOS device screens only? I can sync specific styling approach in sync with @imollov to solve this issue (briefly: to have first and last buttons left and right borders otside the viewport and the bottom border color changed to the color of background).
@davidyuk @maxkpower 
Screenshot_7

**Comment by davidyuk** [comment]
The latest version looks this way

Screenshot 2021-04-23 at 23 25 53

**Review by etharner — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
Checked in Safari and FF mobile browser, LGTM.

**Comment by davidyuk** [comment]
I think it is not fine, but it can't be caused by this PR.

**Pull request merged**
