### PR TITLE
Hotfix: Adjust send modal qr code scanning

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
LGTM

**Review by pstachel — APPROVED** [review]

**Comment by CedrikNikita** [comment]
> For me its not working with tokens. It can scan and detect the address but it does not select the token automatically. It still displayed ae. 

Does the device you scanning with have the same network chosen as the device you are scanning from?

**Comment by csiarab** [comment]
I was trying to scan a token from a different network. So scanning tokens works. 
As for the issue with the disappearing qr code i was using the wallet on chrome on a windows laptop. 
I will retest it again.

**Comment by CedrikNikita** [comment]
> Also sometimes the qr code disappears and reappears after a few seconds 

This PR is not changing qr code generation, and this file in general.

**Comment by csiarab** [comment]
In that case Lgtm. i can scan the qr codes.

**Comment by paolomolo** [comment]
LGTM as well

**Pull request merged**
