### PR TITLE
Compatibility with latest Node.js 12 LTS

### PR DESCRIPTION
**Pull request by vmangelovv**

### CODE REVIEW

**Comment by mradkov** [comment]
I will postpone merging this for the next release as it might open unexpected behavior somewhere else.

**Comment by davidyuk** [comment]
Actually, I'm using v12.16.1 and the wallet builds fine 🤷‍♀️

**Comment by mradkov** [comment]
> Actually, I'm using v12.16.1 and the wallet builds fine 🤷‍♀️

Several people already complained it had build issues with v12.

**Comment by mradkov** [comment]
Can you resolve the conflicts?

**Pull request merged**
