### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by mradkov**
# 0.5.0 (2020-12-22)

## Release highlights

This release includes lots of performance improvements and bugfixes. The new functionalities this release brings will allow users to set permissions per domain/application they use with their superhero wallet (setting up spending limits and allowances per day, general spending limit without confirmation, confirmation settings for popups - `display` or `auto confirm` requests for message signing and spend transactions from applications.

Supports and proper handling of deeplinks and signature scheme required for new posts on superhero (which do not require tip to be send in order to post).

### Bugfixes 🐞 
- [#738](https://github.com/aeternity/superhero-wallet/pull/738): Update available token balances upon switching networks
- [#734](https://github.com/aeternity/superhero-wallet/pull/734): Added visualization for contract call transactions 
- [#736](https://github.com/aeternity/superhero-wallet/pull/736): Added a verbose validation for Tip component 
- [#742](https://github.com/aeternity/superhero-wallet/pull/742): DetailsItem: Keep items in wallet bounds 
- [#717](https://github.com/aeternity/superhero-wallet/pull/717): Fix firefox design related issues 
- [#725](https://github.com/aeternity/superhero-wallet/pull/725): logger: Fix handling vue errors 
- [#718](https://github.com/aeternity/superhero-wallet/pull/718): Intro: Adjust markup 
- [#706](https://github.com/aeternity/superhero-wallet/pull/706): QrCodeReader: Display Header menus 
- [#694](https://github.com/aeternity/superhero-wallet/pull/694): PermissionSettings: Simplify and fix validation 
- [#649](https://github.com/aeternity/superhero-wallet/pull/649): persistState: Explicitly mark that cloneDeep hack is needed for Firefox 
- [#678](https://github.com/aeternity/superhero-wallet/pull/678): Fix sending an error report 
- [#673](https://github.com/aeternity/superhero-wallet/pull/673): Fix message sign popups constantly appearing 
- [#669](https://github.com/aeternity/superhero-wallet/pull/669): Fix address displaying on several screens 
- [#737](https://github.com/aeternity/superhero-wallet/pull/737): Fix migration and iframe permissions 
- [#747](https://github.com/aeternity/superhero-wallet/pull/747): wallet.js: Affect args to make it inserted into function
- [#750](https://github.com/aeternity/superhero-wallet/pull/750): logger: Handle user rejection error
- [#751](https://github.com/aeternity/superhero-wallet/pull/751): permissions.js: Add try/catch for iframe connection popup

### Features ✨ 
- [#584](https://github.com/aeternity/superhero-wallet/pull/584): Add per-domain permissions for applications 
- [#640](https://github.com/aeternity/superhero-wallet/pull/640): Witdraw fungible tokens 
- [#682](https://github.com/aeternity/superhero-wallet/pull/682): Enable tip/retip using deeplinks with FT and v1/2/3 tips 
- [#749](https://github.com/aeternity/superhero-wallet/pull/749): Added indicator for copied address in invite links page

### Maintenance 🚧 
- [#556](https://github.com/aeternity/superhero-wallet/pull/556): Make pending transaction polling more accurate 
- [#636](https://github.com/aeternity/superhero-wallet/pull/636): Remove inline styles 
- [#614](https://github.com/aeternity/superhero-wallet/pull/614): Update eslint packages 
- [#643](https://github.com/aeternity/superhero-wallet/pull/643): Fix Avatar component 
- [#648](https://github.com/aeternity/superhero-wallet/pull/648): Revert "popup: Remove extra wrapper around unwatch" 
- [#642](https://github.com/aeternity/superhero-wallet/pull/642): Refactor SecuritySettings page 
- [#650](https://github.com/aeternity/superhero-wallet/pull/650): Simplify resetting by reloading page after that 
- [#654](https://github.com/aeternity/superhero-wallet/pull/654): Refactor Modal component 
- [#562](https://github.com/aeternity/superhero-wallet/pull/562): General refactoring 
- [#677](https://github.com/aeternity/superhero-wallet/pull/677): Travis build process improvements 
- [#683](https://github.com/aeternity/superhero-wallet/pull/683): Refactoring name auctions
- [#684](https://github.com/aeternity/superhero-wallet/pull/684): Refactor names 
- [#676](https://github.com/aeternity/superhero-wallet/pull/676): Cleanup global styles 
- [#686](https://github.com/aeternity/superhero-wallet/pull/686): calculateFee: Don't calculate max fee 
- [#709](https://github.com/aeternity/superhero-wallet/pull/709): Refactor permissions, add Vuex to extension backend 
- [#652](https://github.com/aeternity/superhero-wallet/pull/652): Make topBlockHeight and balance observables 
- [#719](https://github.com/aeternity/superhero-wallet/pull/719): Remove appVue keys 
- [#707](https://github.com/aeternity/superhero-wallet/pull/707): General refactoring 
- [#724](https://github.com/aeternity/superhero-wallet/pull/724): Optimized send tip method 
- [#728](https://github.com/aeternity/superhero-wallet/pull/728): Wait pending transactions mined if sdk initialized 
- [#726](https://github.com/aeternity/superhero-wallet/pull/726): Transactions: Load transactions only if previous are loaded 
- [#721](https://github.com/aeternity/superhero-wallet/pull/721): Fix sdk of wallet in reverse frame  
- [#715](https://github.com/aeternity/superhero-wallet/pull/715): Cleanup CSS styles: remove all !important modifiers.
- [#741](https://github.com/aeternity/superhero-wallet/pull/741): Fungible Tokens: Middleware CORS issue workaround

### Other changes💡
- [#743](https://github.com/aeternity/superhero-wallet/pull/743): Tour: Revert changes to propertires in steps 
- [#746](https://github.com/aeternity/superhero-wallet/pull/746): Use GitHub Actions instead of Travis 
- [#739](https://github.com/aeternity/superhero-wallet/pull/739): Update dependencies 
- [#637](https://github.com/aeternity/superhero-wallet/pull/637): SecuritySettings: Remove usage of a non-existent component 
- [#730](https://github.com/aeternity/superhero-wallet/pull/730): Adjust Account page 
- [#722](https://github.com/aeternity/superhero-wallet/pull/722): Make back button go up in the hierarchy 
- [#700](https://github.com/aeternity/superhero-wallet/pull/700): Set language on App created 
- [#713](https://github.com/aeternity/superhero-wallet/pull/713): ImportAccount: Show only Loading component on loading 
- [#671](https://github.com/aeternity/superhero-wallet/pull/671): Remove outdated tokens pages and store 
- [#688](https://github.com/aeternity/superhero-wallet/pull/688): Send: Trim entered address 
- [#668](https://github.com/aeternity/superhero-wallet/pull/668): Fetch prefered name 
- [#693](https://github.com/aeternity/superhero-wallet/pull/693): Refactor amount validation in Retip page 
- [#675](https://github.com/aeternity/superhero-wallet/pull/675): Extract TokenAmount component 
- [#685](https://github.com/aeternity/superhero-wallet/pull/685): Fix "Invalid date" of pending transactions, and refactoring 
- [#657](https://github.com/aeternity/superhero-wallet/pull/657): Transactions: Check need to fetch transactions if transactions or displayMode changes

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
The error connecting to a node (mainnet) in web wallet is still reproducible (FF, Safari, Brave):
FF unable connect to the node

More numbers are displayed after the dot (in tokens value):
more numbers

An error checking Activity transactions in the testnet: 

error in testnet
eror testnet


An error in remove account when clicking on Cancel: 
remove account - cancel
error cancel delete acc
2 error cancel
error 3

Web wallet:
Send tip - pass
Claim tip - pass
Activity - not displayed due to a problem connecting to the node
Invite link - pass
Top up - pass 
Withdraw - pass, via scan - pass
Register a name - pass but not displayed due to a problem connecting to the node
Tokens - pass
Settings - pass
FT: Tip - pass
Withdraw - pass

**Review by davidyuk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
FF extension:
Send Tip - pass
Claim Tip - pass
Top Up - pass (connection with Jelly Swap - pass)
Activity - N/A
Withdraw - pass, via scan QR - pass
Names - N/A, Register a name - pass, but not displayed
Invite link - pass
Settings: 
Language - pass
Security&Privacy - pass
Networks: connect to Testnet - pass, connect to Mainnet - failed (Unable to connect to choose node)
Permission Settings - pass
Tip via Twitter button - pass
Tip via Youtube button - pass
Tip/retip on the superhero feed - pass
FT: Tip - pass
Retip - pass
Withdraw - pass

Unable to connect to choose node:

FF ext

The white stripe in FF extension: 
white stripe in FF

An error in remove account when clicking on Cancel:
FF err

I also noticed that after switching from testnet to mainnet, all available FTs are displayed in my wallet. Didn't see FTs when I first entered the wallet. I need to switch between networks to see FT in a wallet on the main network:
all tokens

**Comment by Liubov-crypto** [comment]
Chrome extension: 
Send Tip - pass
Claim Tip - pass
Top Up - pass (connection with Jelly Swap - pass)
Activity - pass
Withdraw - pass, via scan QR- pass
Names: set name pointer, extend, Set as default name - pass
Register a name - pass
Invite link - pass
Settings: 
Language - pass
Security&Privacy - pass
Networks - pass
Permission Settings - Pass
Tip via Twitter button - pass
Tip via Youtube button - pass
Tip/Retip on the sh feed - pass
Remove account - Error - when removing an account

**Comment by Liubov-crypto** [comment]
Iframe wallet: 
Send Tip - pass
Claim Tip - pass
Top Up - pass
Activity - pass
Withdraw - pass, via scan QR code - failed
Names: set name pointer, extend, Set as default name - pass
Register a name (testnet)- pass 
Invite link - pass
Settings: 
Language - pass
Security&Privacy - pass
Networks - pass
Permission Settings - failed
FT: Tip - pass
Withdraw - pass

Got this error in Permission Settings when trying to change limits:
error in settings iframe
error in iframe
error in iframe2

Got this error when trying to withdraw via scan QR code. I allowed superhero.com to use my camera: 
error camera permissions
error 1 camera
error 2 camera

The white stripe in FF: 
white stripe in iframe wallet

**Review by davidyuk — APPROVED** [review]

**Pull request merged**
