### PR TITLE
Change checkbox-unchecked icons color

### PR DESCRIPTION
**Pull request by etharner**
From suggestion in #497.

### CODE REVIEW

**Comment by etharner** [comment]
Actually, for my eyes I don't see much clearer with new color.
Also, it looks like all checkboxes have .iframe class in iframe/web/extension versions, so .svg without iframe is not used anywhere. @mradkov @onvisions Should we just stay with one style for all checkboxes and what color should we choose? Because there are 2 colors for unchecked checkboxes: `#1d1e27` and  `#6a8ebe`.

**Review by mradkov — DISMISSED** [review]
LGTM.

**Comment by etharner** [comment]
> LGTM.

Can we discuss my comment please?

**Comment by mradkov** [comment]
> Actually, for my eyes I don't see much clearer with new color.
> Also, it looks like all checkboxes have .iframe class in iframe/web/extension versions, so .svg without iframe is not used anywhere. @mradkov @onvisions Should we just stay with one style for all checkboxes and what color should we choose? Because there are 2 colors for unchecked checkboxes: `#1d1e27` and `#6a8ebe`.

Let's keep it as suggested in #497.

We will revisit this when we extract superhero components to package.

**Comment by onvisions** [comment]
@mradkov @etharner 
I created styles for the checkbox and radio buttons so they will be clearly visible ([colors, sizes and styles in XD source](https://nx3594.your-storageshare.de/apps/files/?dir=/P1/Superhero/Superhero.com/XD%20Source/0.%20Components/Checkbox%20and%20Radio&fileid=771589))

#6a8ebe probably has remained in the code from previous (very early versions of the wallet) because I don't remember a plaxe whre we are currently using this color.

1  Checkbox - Radio

**Comment by mradkov** [comment]
> @mradkov @etharner
> I created styles for the checkbox and radio buttons so they will be clearly visible ([colors, sizes, and styles in XD source](https://nx3594.your-storageshare.de/apps/files/?dir=/P1/Superhero/Superhero.com/XD%20Source/0.%20Components/Checkbox%20and%20Radio&fileid=771589))
> 
> `#6a8ebe` probably has remained in the code from previous (very early versions of the wallet) because I don't remember a place where we are currently using this color.
> 
> 1 Checkbox - Radio

@etharner can you then revisit this?

**Review by mradkov — APPROVED** [review]

**Pull request merged**
