### PR TITLE
release: v0.7.2

### PR DESCRIPTION
**Pull request by kenodressel**

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]
ok as far as I can see

**Review by davidyuk — APPROVED** [review]
looks good to me

**Comment by Liubov-crypto** [comment]
Web wallet: 
Login to the wallet - pass
Create a new wallet - pass
Send/withdraw ae - pass
Send via scan QR - pass
Receive - pass
Change currency - pass
Copy address - pass
Send tip - pass
Activity history - pass
TX details - pass
Register a name - pass
Generate invite link - pass
Top up - pass
Claim back - pass
Change network - pass
Settings:
Change language - pass
Security&Privacy - pass
Change network - pass
Permission settings - pass
Remove account - pass
Save error log - pass

Some transactions are processed very slowly - send Tip, withdraw, extend name. 

Got this error after registering a name: 
error when change networks

Strange transaction date: 
tr
Hash: th_25RrZUGXjM2F43X9t1UAPBh5zCo2Hzq8GPvVq14dRGU8vCjSY7

Truncated text in extension:
truncated text in extension

The extension does not connect to Voting. endless loading, no pop-ups:
connection with Voting

**Comment by Liubov-crypto** [comment]
Chrome/FF extensions:
Login to the wallet - pass
Create new wallet - pass
Send/withdraw ae - pass 
Send via scan QR - pass 
Receive ae - pass 
Change currency - pass 
Copy - address - pass 
Send tip - pass 
Send tip via Twitter button - pass
Claim tip - pass 
Activity history - pass 
TX details - pass 
Register a name - pass 
Set name pointer - pass
Extend - pass
Generate invite link - pass 
Top up - pass 
Claim back - pass 

Settings:
Change language - pass 
Security&Privacy - pass 
Change network - pass 
Permission settings - pass 
Remove account - pass 
Save error log - pass 

I noticed that after transactions with names (extend, set name pointer), the name set as the default wallet itself changes to another name.
Processing the transaction "send a tip" is very slow on the superhero feed.

In general LGTM, with the exception of minor bugs that I described above.

**Comment by Liubov-crypto** [comment]
Error when sending a tip on superhero feed: 
ddd
cons

Claim tip - the operation was successful, but there is still no tokens. The amount of tokens in the wallet has not changed.

**Pull request merged**
