### PR TITLE
Release 0.5.1

### PR DESCRIPTION
**Pull request by mradkov**
### Features

* add new notifications design ([5fa43b0](https://github.com/aeternity/superhero-wallet/commit/5fa43b00c13e1c762f68088fcba120a38b12c7e4))
* show error if AENS name or address is invalid ([4d3e6c0](https://github.com/aeternity/superhero-wallet/commit/4d3e6c09b6284ad77780ccd8a691a5778c463411))
* warn tipping http urls ([65d3025](https://github.com/aeternity/superhero-wallet/commit/65d302591d05a8380a0cc81bc9e265cf71e9f85b))
* **changelog:** build using standard-version ([505412b](https://github.com/aeternity/superhero-wallet/commit/505412b59fff07e3879835e5bef86457ab595ea7))

### Bug Fixes

* handle the default name responce correctly ([68192a8](https://github.com/aeternity/superhero-wallet/commit/68192a87ba03ff8f48b1ed2f55187a8d168c2292))
* **account:** hide chain name scrollbar ([1dd7029](https://github.com/aeternity/superhero-wallet/commit/1dd7029170f765e0ae218a9dddfab010e6c774c1))
* **global:** revert scrollbar width until rebranding ([c4dfca3](https://github.com/aeternity/superhero-wallet/commit/c4dfca3df2a3d3431109f7a4ce0b118d343d8923))
* **ios:** header titles overlap when navigating ([4fe0dbf](https://github.com/aeternity/superhero-wallet/commit/4fe0dbf96b9cd062c029648831a88c8f6b3f6b79))
* copy address not working ([3aec392](https://github.com/aeternity/superhero-wallet/commit/3aec392555a95b2737bddd934adc6b77cde20812))
* hide chain name scrollbars on firefox ([d2b0d79](https://github.com/aeternity/superhero-wallet/commit/d2b0d79f8599dfa08d46c3c846885bb8c075fba5))
* incorrect amount on retip success ([fd8f3cb](https://github.com/aeternity/superhero-wallet/commit/fd8f3cb68a193ecdfcdedf01978960faeeb96100))
* rename background script entry ([851b359](https://github.com/aeternity/superhero-wallet/commit/851b35927e762063a06504a5e87c3c96a390fa63))
* toggle showable types of notification properly ([a08a763](https://github.com/aeternity/superhero-wallet/commit/a08a76348b2cad56fb5ed3bf006a91aa59b18627))
* **account:** long chain names outside viewport ([a96829d](https://github.com/aeternity/superhero-wallet/commit/a96829d235a7b14b5d60a32424c829918c702077))
* **commitlint:** run commitlint from first valid commit ([404972e](https://github.com/aeternity/superhero-wallet/commit/404972ea13d4d55f33d2fc402b88ff373012cac9))
* **global:** don't display scrollbar on blink and webkit engines ([7755be6](https://github.com/aeternity/superhero-wallet/commit/7755be6489ff69140ecdeba4d676f7adf3574892))
* **global:** don't display scrollbar on blink and webkit engines ([f967207](https://github.com/aeternity/superhero-wallet/commit/f967207a35aa91c590d1e42d5ee08637c783256b))
* **modal:** show only 1 small modal at a time ([05a6f81](https://github.com/aeternity/superhero-wallet/commit/05a6f81cffdf5c8ebafba028296f6cc7f0ee3e63))
* **notifications:** don't display backup after importing an account ([9f2282b](https://github.com/aeternity/superhero-wallet/commit/9f2282bc9d66e0db1898ff5e2f06feac0319d6ef))
* set success message as a div ([9b19b15](https://github.com/aeternity/superhero-wallet/commit/9b19b1558a955ad9a82fdf0b49e26926654a193d))

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
Web wallet: 
Generate new wallet - pass
Login into the wallet - pass
Change tokens - pass 
Change currency - pass 
Copy address - pass
Send Tip - pass
Send Tip to HTTP - failed (did not receive any warning when sending tokens)
Retip - pass
Claim Tip - pass 
Top Up - pass
Connection with Jelly Swap - no for web wallet
Withdraw (Send) - pass, via Scan QR code - pass
Activity - pass, Sort by date - pass
Tokens: search - pass
Send - pass 
Receive - pass 
Names: 
Set name pointer - pass 
Extend - pass 
Set as default name - pass 
Register name - I registered a name, but it disappeared from the wallet
Invite link:
Create - pass 
Top up - pass
Claim back - pass 
Settings: 
Language - pass 
Security&Privacy - pass 
Permission Settings - pass 
Remove account - pass

Networks - error when switching to the testnet:
switch to the testnet
testnet switch err
testnet switch err 2

There was an error when I registered a name (name disappeared from the wallet):

error when registr a name
err name reg

The transaction does not immediately appear in the Claimed field, there are only for the previous date (although I performed claiming):
claimed transaction

I leave wallet for a while and got this error - add error t screen 

error t
error t1
error t 2

FT design is broken: 
FT design broken
FT design
cutted FT design

Error in iframe wallet: 
err in iframe wallet

**Comment by Liubov-crypto** [comment]
FF extension: 
Generate new wallet - pass 
Login into the wallet - pass 
Change tokens - pass 
Change currency - pass 
Copy address - pass 
Send Tip - pass 
Send Tip to HTTP - pass (receive a warning) 
Tip via Twitter/Youtube button 
Retip - pass 
Claim Tip - error (The transaction does not immediately appear in the Claimed field, there are only for the previous date) 
Top Up - pass
connection with Jelly Swap - pass 
Withdraw (Send) - pass, via Scan QR code - pass 
Activity - pass, sort by date - pass 
Tokens: search - pass 
Send - pass 
Receive - pass 
Names: 
Set name pointer - pass 
Extend - pass 
Set as default name - pass 
Register name - pass  (in the testnet) 
Invite link:
Create - pass 
Top up - pass 
Claim back - pass 
Settings: 
Language - pass 
Security&Privacy - pass 
Networks - error when switch to the testnet
Permission Settings - pass 
Remove account - pass 

FF- error when switching to the testnet: 
error FF

I noticed that after claim a tip transaction, the amount that was added, disappeared from the wallet. Transaction rolled back:

err with ckaiming
claim err 2

Received FT not appear in the Top Up field:

top up

FT design is broken:
ft des

**Comment by Liubov-crypto** [comment]
Chrome extension:
Generate new wallet - pass 
Login into the wallet - pass 
Change tokens - pass 
Change currency - pass 
Copy address - pass 
Send Tip - pass 
Send Tip to HTTP - pass (receive a warning) 
Tip via Twitter/Youtube button - pass
Retip - pass 
Claim Tip - error  (The transaction does not immediately appear in the Claimed field, there are only for the previous date + rolling back)
Top Up - pass  (FT are not displayed in Top Up field)
connection with Jelly Swap - pass 
Withdraw (Send) - pass, via Scan QR code - pass 
Activity - pass, sort by date - pass 
Tokens: search - pass 
Send - pass 
Receive - pass 
Names:
Set name pointer - pass 
Extend - pass 
Set as default name - pass 
Register name - pass 
Invite link:
Create - pass 
Top up - pass 
Claim back - pass 
Settings:
Language - pass 
Security&Privacy - pass 
Networks - pass 
Permission Settings - pass 
Remove account - pass 

The issue with scrollbar in a Chrome extension:
scrollbar

Also, the same bugs were in FF extension: 
- Received FT not appear in the Top Up field. 
- FT design is broken.
- Claim Tip transaction rolling back.

**Comment by mradkov** [comment]
> Chrome extension:
> Generate new wallet - pass
> Login into the wallet - pass
> Change tokens - pass
> Change currency - pass
> Copy address - pass
> Send Tip - pass
> Send Tip to HTTP - pass (receive a warning)
> Tip via Twitter/Youtube button - pass
> Retip - pass
> Claim Tip - error (The transaction does not immediately appear in the Claimed field, there are only for the previous date + rolling back)
> Top Up - pass (FT are not displayed in Top Up field)
> connection with Jelly Swap - pass
> Withdraw (Send) - pass, via Scan QR code - pass
> Activity - pass, sort by date - pass
> Tokens: search - pass
> Send - pass
> Receive - pass
> Names:
> Set name pointer - pass
> Extend - pass
> Set as default name - pass
> Register name - pass
> Invite link:
> Create - pass
> Top up - pass
> Claim back - pass
> Settings:
> Language - pass
> Security&Privacy - pass
> Networks - pass
> Permission Settings - pass
> Remove account - pass
> 
> The issue with scrollbar in a Chrome extension:
> scrollbar
> 
> Also, the same bugs were in FF extension:
> 
> * Received FT not appear in the Top Up field.
> * FT design is broken.
> * Claim Tip transaction rolling back.

@Liubov-crypto 

Claim tip is async and cannot appear immediately in the history of transactions. Futhermore we are using a `payforTx` service to cover for transaction fees for users that do not have balance for this at the time of claiming. This means the transaction originator is not their account rather the `payforTx` service. These claims are served to the wallet to display in the transaction history but with some delay.

**Comment by Liubov-crypto** [comment]
> > Chrome extension:
> > Generate new wallet - pass
> > Login into the wallet - pass
> > Change tokens - pass
> > Change currency - pass
> > Copy address - pass
> > Send Tip - pass
> > Send Tip to HTTP - pass (receive a warning)
> > Tip via Twitter/Youtube button - pass
> > Retip - pass
> > Claim Tip - error (The transaction does not immediately appear in the Claimed field, there are only for the previous date + rolling back)
> > Top Up - pass (FT are not displayed in Top Up field)
> > connection with Jelly Swap - pass
> > Withdraw (Send) - pass, via Scan QR code - pass
> > Activity - pass, sort by date - pass
> > Tokens: search - pass
> > Send - pass
> > Receive - pass
> > Names:
> > Set name pointer - pass
> > Extend - pass
> > Set as default name - pass
> > Register name - pass
> > Invite link:
> > Create - pass
> > Top up - pass
> > Claim back - pass
> > Settings:
> > Language - pass
> > Security&Privacy - pass
> > Networks - pass
> > Permission Settings - pass
> > Remove account - pass
> > The issue with scrollbar in a Chrome extension:
> > scrollbar
> > Also, the same bugs were in FF extension:
> > 
> > * Received FT not appear in the Top Up field.
> > * FT design is broken.
> > * Claim Tip transaction rolling back.
> 
> @Liubov-crypto
> 
> Claim tip is async and cannot appear immediately in the history of transactions. Futhermore we are using a `payforTx` service to cover for transaction fees for users that do not have balance for this at the time of claiming. This means the transaction originator is not their account rather the `payforTx` service. These claims are served to the wallet to display in the transaction history but with some delay.

ok, got it. 
Rechecked, now I see transactions that were conducted a few hours ago:
claim tip

**Comment by mradkov** [comment]
> > > Chrome extension:
> > > Generate new wallet - pass
> > > Login into the wallet - pass
> > > Change tokens - pass
> > > Change currency - pass
> > > Copy address - pass
> > > Send Tip - pass
> > > Send Tip to HTTP - pass (receive a warning)
> > > Tip via Twitter/Youtube button - pass
> > > Retip - pass
> > > Claim Tip - error (The transaction does not immediately appear in the Claimed field, there are only for the previous date + rolling back)
> > > Top Up - pass (FT are not displayed in Top Up field)
> > > connection with Jelly Swap - pass
> > > Withdraw (Send) - pass, via Scan QR code - pass
> > > Activity - pass, sort by date - pass
> > > Tokens: search - pass
> > > Send - pass
> > > Receive - pass
> > > Names:
> > > Set name pointer - pass
> > > Extend - pass
> > > Set as default name - pass
> > > Register name - pass
> > > Invite link:
> > > Create - pass
> > > Top up - pass
> > > Claim back - pass
> > > Settings:
> > > Language - pass
> > > Security&Privacy - pass
> > > Networks - pass
> > > Permission Settings - pass
> > > Remove account - pass
> > > The issue with scrollbar in a Chrome extension:
> > > scrollbar
> > > Also, the same bugs were in FF extension:
> > > 
> > > * Received FT not appear in the Top Up field.
> > > * FT design is broken.
> > > * Claim Tip transaction rolling back.
> > 
> > 
> > @Liubov-crypto
> > Claim tip is async and cannot appear immediately in the history of transactions. Futhermore we are using a `payforTx` service to cover for transaction fees for users that do not have balance for this at the time of claiming. This means the transaction originator is not their account rather the `payforTx` service. These claims are served to the wallet to display in the transaction history but with some delay.
> 
> ok, got it.
> Rechecked, now I see transactions that were conducted a few hours ago:
> claim tip

✌️ I've rebased this PR with the latest fixes from develop, please do re-check the new build once again after the CI is done.

**Comment by Liubov-crypto** [comment]
Web wallet: 
Generate new wallet - pass 
Login into wallet - pass 
Change tokens - pass 
Change currency - pass 
Copy address - pass 
Send Tip - pass 
Send Tip to http - pass (receive warning) 
Retip - pass 
Claim Tip - pass 
Top Up (with ae and FT)- pass
Withdraw (Send) - pass, via Scan QR code - pass 
Activity - pass, sort by date - pass 
Tokens: search - pass 
Send - pass 
Receive - pass 
Names: 
Set name pointer - pass 
Extend - pass 
Set as default name - pass 
Register name - pass (in the testnet)
Invite link:
Create - pass 
Top up - pass 
Claim back - pass 
Settings: 
Language - pass 
Security&Privacy - pass 
Networks - pass 
Permission Settings - pass
Remove account - pass 

Transactions with FT are not displayed in Activity (Send, Received), :
FT tokens
although I can see these transactions in my android app.

Small design bug: 
Safari new wallet

**Review by Liubov-crypto — COMMENTED** [review]
FF/Chrome extensions:
Generate new wallet - pass
Login into wallet - pass
Change tokens - pass
Change currency - pass 
Copy address - pass 
Send Tip - pass 
Send Tip to http - pass (receive a warning)
Tip via Twitter/Youtube button - pass
Retip - pass 
Claim Tip - pass 
Top Up with ae tokens/FT - pass 
Connection with Jelly Swap - pass 
Withdraw (Send) - pass, via Scan QR code - pass 
Activity - pass, sort by date - pass 
Tokens: search - pass 
Send - pass 
Receive - pass 
Names: 
Set name pointer - pass 
Extend - pass 
Set as default name - pass 
Register name - pass (in the testnet)
Invite link:
Create - pass 
Top up - pass
Claim back - pass
Settings: 
Language - pass 
Security&Privacy - pass 
Networks - pass 
Permission Settings - pass 
Remove account - pass

There was an issue registering the name in the testnet, but the name was registered. 
name error in chrome ext
errr when registered a name in testnet

**Comment by onvisions** [comment]
@mradkov  @etharner 
There is a small design bug described above. However the design mockups provided cover the case of longer text message. So it just needs not to be hyphened but the word "phrase" should go on a new line instead. In the comming next version of the wallet UI design the text-font will be 14px instead of 15px so this will release even more space for the messages.
The other thing missing is the full blockchain address. There is placeholder for this also. 
Basically we have two cases: **1. Fellow Superhero** (if the user has no .chain name) + **full blockchain address** OR **2. name.chain** + **full blockchain address**. Blockchain address (and .chain name) sholud lead to user blockchain account opened in blockchain explorer (as soon as this functionality operates in a correct manner). If there is problem with address lenghth (although design is tested with real addresses) it should be shortened (cut) in the same way that we discussed to deal with very long .chain names.

**Comment by mradkov** [comment]
> I noticed that the balance of tokens is randomly changing in the wallet (Chrome extension). I recorded a video so you can see the changes. Perhaps this is due to the delay in the claim tokens transaction, as was described above.
> 
>  2021-02-03.3.01.38.mov

@Liubov-crypto can you create an issue for this. I think its not strictly related to this release.

**Comment by mradkov** [comment]
> @mradkov @etharner
> There is a small design bug described above. However the design mockups provided cover the case of longer text message. So it just needs not to be hyphened but the word "phrase" should go on a new line instead. In the comming next version of the wallet UI design the text-font will be 14px instead of 15px so this will release even more space for the messages.
> The other thing missing is the full blockchain address. There is placeholder for this also.
> Basically we have two cases: **1. Fellow Superhero** (if the user has no .chain name) + **full blockchain address** OR **2. name.chain** + **full blockchain address**. Blockchain address (and .chain name) sholud lead to user blockchain account opened in blockchain explorer (as soon as this functionality operates in a correct manner). If there is problem with address lenghth (although design is tested with real addresses) it should be shortened (cut) in the same way that we discussed to deal with very long .chain names.

Is this a blocker for this release. As you are describing the new designs will have more changes, so should we spend time on correcting this now or should we roll it and improve on it later?

**Comment by Liubov-crypto** [comment]
> > I noticed that the balance of tokens is randomly changing in the wallet (Chrome extension). I recorded a video so you can see the changes. Perhaps this is due to the delay in the claim tokens transaction, as was described above.
> > 2021-02-03.3.01.38.mov
> 
> @Liubov-crypto can you create an issue for this. I think its not strictly related to this release.

sure, here is it: https://github.com/aeternity/superhero-wallet/issues/804#issue-800366362

**Comment by onvisions** [comment]
@mradkov 
I think that we should remove the hyphening at least (this is the default behaviour of the word-wrap: no breaking words).
And as far as the rest is concerned - we can skip for this release.

**Review by CedrikNikita — COMMENTED** [review]
image

**Comment by imollov** [comment]
> image

Created a fix https://github.com/aeternity/superhero-wallet/pull/809

Also fixes the details view title:
Screenshot 2021-02-04 at 12 53 31

**Pull request merged**
